# Generated by Django 3.0.5 on 2020-06-17 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_type', models.CharField(max_length=255)),
                ('monster_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'monsters',
                'db_table': 'monster',
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('where', models.CharField(max_length=255)),
                ('which_monster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monstertrackerapp.Monster')),
            ],
        ),
    ]
