# Generated by Django 3.0.5 on 2020-06-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monstertrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'verbose_name_plural': 'sightings'},
        ),
        migrations.AddField(
            model_name='monster',
            name='monster_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='sighting',
            table='sighting',
        ),
    ]
